'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase, therapistImageUrl } from '../../lib/supabase';
import Operations from './Operations';

const emptyTherapist = { id:'',name:'',slug:'',age:'',height:'',nomination_fee:0,profile_text:'',manager_comment:'',image_path:'',x_url:'',instagram_url:'',bluesky_url:'',is_published:true,display_order:0,store_ids:[] };
const emptySchedule = { id:'',therapist_id:'',store_id:'',work_date:'',start_time:'',end_time:'',note:'',is_published:true };
function slugify(v){return v.trim().toLowerCase().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'')||`therapist-${Date.now()}`}

export default function AdminPage(){
 const [session,setSession]=useState(null),[email,setEmail]=useState('marron.toyohashi@gmail.com'),[password,setPassword]=useState(''),[isAdmin,setIsAdmin]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[stores,setStores]=useState([]),[therapists,setTherapists]=useState([]),[schedules,setSchedules]=useState([]),[therapistForm,setTherapistForm]=useState(emptyTherapist),[scheduleForm,setScheduleForm]=useState(emptySchedule),[tab,setTab]=useState('operations');
 const loadData=useCallback(async()=>{const [{data:a},{data:b,error:e},{data:c}]=await Promise.all([supabase.from('resort_stores').select('*').order('display_order'),supabase.from('resort_therapists').select('*, resort_therapist_stores(store_id)').order('display_order').order('name'),supabase.from('resort_schedules').select('*, resort_therapists(name), resort_stores(name)').order('work_date').order('start_time')]);if(e)throw e;setStores(a||[]);setTherapists((b||[]).map(x=>({...x,store_ids:(x.resort_therapist_stores||[]).map(r=>r.store_id)})));setSchedules(c||[])},[]);
 useEffect(()=>{let m=true;supabase.auth.getSession().then(async({data})=>{if(!m)return;setSession(data.session);if(data.session){const{data:a}=await supabase.from('resort_admins').select('user_id').eq('user_id',data.session.user.id).maybeSingle();if(a){setIsAdmin(true);await loadData()}}setLoading(false)});const{data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>{m=false;l.subscription.unsubscribe()}},[loadData]);
 const login=async e=>{e.preventDefault();setMessage('ログイン中…');const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error)return setMessage('メールアドレスまたはパスワードを確認してください。');const{data:a}=await supabase.from('resort_admins').select('user_id').eq('user_id',data.user.id).maybeSingle();if(!a){await supabase.auth.signOut();return setMessage('このアカウントにはResort-styleの管理権限がありません。')}setSession(data.session);setIsAdmin(true);await loadData();setMessage('')};
 const saveTherapist=async e=>{e.preventDefault();setSaving(true);try{const p={name:therapistForm.name.trim(),slug:therapistForm.slug?slugify(therapistForm.slug):slugify(therapistForm.name),age:therapistForm.age?Number(therapistForm.age):null,height:therapistForm.height?Number(therapistForm.height):null,nomination_fee:Number(therapistForm.nomination_fee||0),profile_text:therapistForm.profile_text,manager_comment:therapistForm.manager_comment,image_path:therapistForm.image_path||null,x_url:therapistForm.x_url||null,instagram_url:therapistForm.instagram_url||null,bluesky_url:therapistForm.bluesky_url||null,is_published:therapistForm.is_published,display_order:Number(therapistForm.display_order||0)};const q=therapistForm.id?supabase.from('resort_therapists').update(p).eq('id',therapistForm.id).select().single():supabase.from('resort_therapists').insert(p).select().single();const{data:s,error}=await q;if(error)throw error;await supabase.from('resort_therapist_stores').delete().eq('therapist_id',s.id);if(therapistForm.store_ids.length)await supabase.from('resort_therapist_stores').insert(therapistForm.store_ids.map(store_id=>({therapist_id:s.id,store_id})));setTherapistForm(emptyTherapist);await loadData();setMessage('プロフィールを保存しました。')}catch(x){setMessage(`保存できませんでした：${x.message}`)}setSaving(false)};
 const uploadImage=async e=>{const f=e.target.files?.[0];if(!f)return;setSaving(true);const ext=f.name.split('.').pop()||'jpg',path=`${session.user.id}/${crypto.randomUUID()}.${ext}`;const{error}=await supabase.storage.from('resort-therapists').upload(path,f);if(error)setMessage(`画像をアップロードできませんでした：${error.message}`);else setTherapistForm(x=>({...x,image_path:path}));setSaving(false)};
 const saveSchedule=async e=>{e.preventDefault();setSaving(true);const p={therapist_id:scheduleForm.therapist_id,store_id:Number(scheduleForm.store_id),work_date:scheduleForm.work_date,start_time:scheduleForm.start_time||null,end_time:scheduleForm.end_time||null,note:scheduleForm.note,is_published:scheduleForm.is_published};const q=scheduleForm.id?supabase.from('resort_schedules').update(p).eq('id',scheduleForm.id):supabase.from('resort_schedules').upsert(p,{onConflict:'therapist_id,work_date'});const{error}=await q;if(error)setMessage(`出勤予定を保存できませんでした：${error.message}`);else{setScheduleForm(emptySchedule);await loadData();setMessage('出勤店舗と時間を保存しました。')}setSaving(false)};
 const sortedSchedules=useMemo(()=>[...schedules].sort((a,b)=>`${a.work_date}${a.start_time||''}`.localeCompare(`${b.work_date}${b.start_time||''}`)),[schedules]);
 if(loading)return <main className="admin-shell"><p>確認中…</p></main>;
 if(!session||!isAdmin)return <main className="admin-shell admin-login-shell"><form className="admin-panel admin-login" onSubmit={login}><p className="admin-kicker">RESORT-STYLE</p><h1>管理画面ログイン</h1><label>メールアドレス<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>パスワード<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="admin-primary">ログイン</button>{message&&<p className="admin-message">{message}</p>}<a href="/">← サイトへ戻る</a></form></main>;
 return <main className="admin-shell"><header className="admin-header"><div><p className="admin-kicker">RESORT-STYLE</p><h1>店舗運営ダッシュボード</h1></div><div className="admin-header-actions"><a href="/" target="_blank">サイトを確認</a><button onClick={()=>supabase.auth.signOut().then(()=>location.reload())}>ログアウト</button></div></header>
 <nav className="admin-tabs admin-main-tabs"><button className={tab==='operations'?'active':''} onClick={()=>setTab('operations')}>顧客・予約・売上・稼働</button><button className={tab==='therapists'?'active':''} onClick={()=>setTab('therapists')}>プロフィール管理</button><button className={tab==='schedules'?'active':''} onClick={()=>setTab('schedules')}>出勤・店舗管理</button><a href="/admin/therapist-mypages" style={{display:'inline-flex',alignItems:'center',justifyContent:'center',padding:'10px 14px',borderRadius:10,textDecoration:'none',fontWeight:700}}>女の子マイページ管理</a></nav>{message&&<p className="admin-message">{message}</p>}
 {tab==='operations'&&<Operations stores={stores} therapists={therapists} schedules={schedules} notify={setMessage}/>} 
 {tab==='therapists'&&<><form className="admin-panel admin-form" onSubmit={saveTherapist}><div className="admin-panel-title"><h2>{therapistForm.id?'プロフィール編集':'女の子を新規登録'}</h2></div><div className="admin-grid"><label>名前<input value={therapistForm.name} onChange={e=>setTherapistForm({...therapistForm,name:e.target.value})} required/></label><label>URL用ID<input value={therapistForm.slug} onChange={e=>setTherapistForm({...therapistForm,slug:e.target.value})}/></label><label>年齢<input type="number" min="18" value={therapistForm.age} onChange={e=>setTherapistForm({...therapistForm,age:e.target.value})}/></label><label>身長<input type="number" value={therapistForm.height} onChange={e=>setTherapistForm({...therapistForm,height:e.target.value})}/></label><label>指名料<input type="number" value={therapistForm.nomination_fee} onChange={e=>setTherapistForm({...therapistForm,nomination_fee:e.target.value})}/></label></div><fieldset><legend>在籍店舗</legend>{stores.map(s=><label key={s.id}><input type="checkbox" checked={therapistForm.store_ids.includes(s.id)} onChange={e=>setTherapistForm({...therapistForm,store_ids:e.target.checked?[...therapistForm.store_ids,s.id]:therapistForm.store_ids.filter(id=>id!==s.id)})}/>{s.name}</label>)}</fieldset><label>プロフィール画像<input type="file" onChange={uploadImage}/></label><label>店長からの紹介<textarea value={therapistForm.manager_comment} onChange={e=>setTherapistForm({...therapistForm,manager_comment:e.target.value})}/></label><label>プロフィール本文<textarea value={therapistForm.profile_text} onChange={e=>setTherapistForm({...therapistForm,profile_text:e.target.value})}/></label><button className="admin-primary" disabled={saving}>プロフィールを保存</button></form><section className="admin-card-list">{therapists.map(x=><article className="admin-person-card" key={x.id}><img src={therapistImageUrl(x.image_path)} alt={x.name}/><div><h3>{x.name}</h3></div><button onClick={()=>{setTherapistForm({...emptyTherapist,...x});window.scrollTo({top:0,behavior:'smooth'})}}>編集</button></article>)}</section></>}
 {tab==='schedules'&&<><form className="admin-panel admin-form" onSubmit={saveSchedule}><h2>出勤予定を追加</h2><div className="admin-grid"><label>女の子<select value={scheduleForm.therapist_id} onChange={e=>setScheduleForm({...scheduleForm,therapist_id:e.target.value})} required><option value="">選択</option>{therapists.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>出勤店舗<select value={scheduleForm.store_id} onChange={e=>setScheduleForm({...scheduleForm,store_id:e.target.value})} required><option value="">選択</option>{stores.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>出勤日<input type="date" value={scheduleForm.work_date} onChange={e=>setScheduleForm({...scheduleForm,work_date:e.target.value})} required/></label><label>開始<input type="time" value={scheduleForm.start_time} onChange={e=>setScheduleForm({...scheduleForm,start_time:e.target.value})}/></label><label>終了<input type="time" value={scheduleForm.end_time} onChange={e=>setScheduleForm({...scheduleForm,end_time:e.target.value})}/></label></div><button className="admin-primary">出勤予定を保存</button></form><section className="admin-schedule-list">{sortedSchedules.map(x=><article key={x.id}><strong>{x.work_date} {x.start_time?.slice(0,5)}〜{x.end_time?.slice(0,5)}</strong><p>{x.resort_therapists?.name}／{x.resort_stores?.name}</p></article>)}</section></>}
 </main>;
}